vivs/urls.py
from django.conf.urls import include, url, patterns
from vivsite import settings
from vivs.views.Project import *


project_url = [
    url(r'^$', DashboardView.as_view(), name ='dashboard'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^works/$', WorksView.as_view(), name='works'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^project/$', ProjectDetailView, name='project_detail'),
    url(r'^task/(?P<pk>\d+)/$', TaskToProjectFilterView.as_view(), name='task_filter_view'),
    url(r'^mentions-legales/$', LegalView.as_view(), name='mentions_legales')
]

urlpatterns = patterns('',
    url(r'^index/', include(project_url, namespace="project")),
)

vivsite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from vivsite import settings




urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('vivs.urls', namespace="vivs_app")),
]

if settings.DEBUG:
    # serve a caricare media sul server urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vivs/models/Image.py
from django.db import models
from vivs.models.Project import Project

class Image(models.Model):

    name = models.CharField(
        verbose_name="Image name",
        max_length=50,
        null=True,
        blank=True
    )

    image = models.ImageField(
        verbose_name = "Project images",
        upload_to = 'project_images/',
        height_field = None,
        width_field = None,
        max_length = 100,
        null = True,
        blank = True
    )

    releted_project = models.ForeignKey(
        Project,
        verbose_name = "Images in this project",
        related_name = "images",
        null=True,
        blank=True
    )

    image_descr = models.TextField(
        verbose_name="Image description",
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = "vivs"
        verbose_name_plural = "Images"

vivs/models/Project.py
from django.core.urlresolvers import reverse_lazy
from django.db import models
from vivs.models.Task import Task

class Project (models.Model):

    name = models.CharField(
        verbose_name = "Project name",
        max_length=50
    )
    cover = models.ImageField(
        verbose_name = "Cover image",
        upload_to = 'cover/',
        height_field = None,
        width_field = None,
        max_length = 100,
        null = True,
        blank = True
    )
    website = models.CharField(
        verbose_name = "Project website",
        max_length=50,
        null=True,
        blank=True
    )

    client = models.CharField(
        verbose_name = "Client",
        max_length = 50
    )

    client_descr = models.TextField(
        verbose_name="Client description",
    )

    tasks = models.ManyToManyField(
        Task,
        verbose_name= "tasksInProject",
        related_name="projects",
        blank = True
    )
    date = models.CharField(
        verbose_name = "Project date",
        max_length=50
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('vivs_app:project:project_detail', kwargs={'pk': self.id})

    class Meta:
        app_label = "vivs"
        #ordering = [ ]
        verbose_name_plural = "Projects"

vivs/models/Task.py
from django.db import models
from django.core.urlresolvers import reverse_lazy


class Task(models.Model):
    name = models.CharField(
        verbose_name="Task",
        max_length = 50
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('vivs_app:project:task_filter_view', kwargs={'pk': self.id})

    class Meta:
        app_label = "vivs"
        verbose_name_plural = "Tasks"

vivs/views/Project.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView, CreateView
from vivs.models.Project import Project, Task

class DashboardView(TemplateView):
    model = Project
    context_object_name = "project_index"
    template_name = "vivs/index.html"

#class ProjectDetailView(DetailView):
 #   model = Project
  #  template_name = "vivs/project_detail.html"
   # context_object_name = "project"*/

class TaskToProjectFilterView(DetailView):
    model = Task
    template_name = "vivs/task_filter.html"
    context_object_name = "task_filter"

class AboutView(TemplateView):
    template_name = "vivs/about.html"

class WorksView(ListView):
    model = Project
    template_name = "vivs/works.html"
    context_object_name = "works"

class ContactView(TemplateView):
    template_name = "vivs/contact.html"

class LegalView(TemplateView):
    template_name = "vivs/mentions-legales.html"

def ProjectDetailView(request):
    project_list = Project.objects.all()
    paginator = Paginator(project_list, 1) # Show 1 project per page

    page = request.GET.get('page')
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        projects = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        projects = paginator.page(paginator.num_pages)

    return render(request, 'vivs/project_detail.html', {'projects': projects})

templates/base.html
{% spaceless %}
{% load bootstrap3 %}
{% load staticfiles %} <!-- per caricare i file della cartella "static" che chiederemo al server di cariare poiche django non legge velocemente altri file diversi da python -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/media/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/media/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/media/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/media/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/media/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/media/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/media/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/media/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/media/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/media/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/media/favicon-194x194.png" sizes="194x194">
    <link rel="icon" type="image/png" href="/media/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/media/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/media/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/media/manifest.json">
    <link rel="mask-icon" href="/media/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/media/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="/media/mstile-144x144.png">
    <meta name="msapplication-config" content="/media/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- Title -->
    <title>{% block TITLE %}Viv-s{% endblock %}</title>

    <!-- Custom styles for this template -->
      {% bootstrap_css %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" >
    <link href="{% static 'css/projectDetails.css' %}" rel="stylesheet" >
    <link href="{% static 'css/about.css' %}" rel="stylesheet" >
</head>

<body>
    {% if request.get_full_path = "/index/" %}
    <object id="svg_sfondo" type="image/svg+xml" data="{% static 'svg/vivsite-opt-img-3-1.svg' %}" class="sfondo">
        Viv-s background <!-- fallback image in CSS -->
    </object>
    {% endif %}
    {% if '/task' in request.path %}
    <object id="svg_sfondo" type="image/svg+xml" data="{% static 'svg/vivsite-opt-img-3-2.svg' %}" class="sfondo">
        Viv-s background <!-- fallback image in CSS -->
    </object>
    {% endif %}
    {% if '/works/' in request.path %}
    <object id="svg_sfondo" type="image/svg+xml" data="{% static 'svg/vivsite-opt-img-3-2.svg' %}" class="sfondo">
        Viv-s background <!-- fallback image in CSS -->
    </object>
    {% endif %}
    <nav id="header" class="navbar navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a id="logo" class="navbar-brand" href="{% url 'vivs_app:project:dashboard' %}"><img src="{% static 'img/logo.png' %}" alt="viv-s logo" /></a>
        </div>
        <div id="navbar-right" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'vivs_app:project:about' %}">about</a></li>
            <li><a href="{% url 'vivs_app:project:works' %}">works</a></li>
            <li><a href="{% url 'vivs_app:project:contact' %}">contacts</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div id="content" class="container-fluid">
      <div class="row">
        <div id="left-section" class="col-sm-3 col-md-2 sidebar"> <!-- class sidebar -->
            {% if '/works/' in request.path %}
                <h4>all works</h4>
                <ul id="all_works" class="works nav nav-sidebar">
                    {% for element in project_list %}
                    <li><a  name="{{element}}" href="http://127.0.0.1:8000/index/project/?page={{ element.id }}">{{element}}</a></li>
                    {% endfor %}
                </ul>
            {% elif '/task/' in request.path %}
                <h4>{{task_filter}} works</h4>
                <ul id="task_works" class="works nav nav-sidebar">
                {% for element in task_filter.projects.all %}
                <li><a  name="{{element}}" href="http://127.0.0.1:8000/index/project/?page={{ element.id }}">{{element}}</a></li>
                {%endfor%}
                </ul>
            {% else %}
                <h4>last works</h4>
                <ul id="last_works" class="works nav nav-sidebar">
                    {% for element in limit_project_list %}
                    <li><a name="{{element}}" href="http://127.0.0.1:8000/index/project/?page={{ element.id }}">{{element}}</a></li>
                    {%endfor%}
                </ul>
            {% endif %}

             {% if not '/works/' in request.path %} <!-- in python se una cosa è  = 0, in booleano = "false" -->
            <h4>tasks</h4>
            <ul id="tasks" class="nav nav-sidebar">
            {% for element in task_list %} <!-- "parcours" = context_object_name in view/Parcours -->
            <li>
                <a href="{% url 'vivs_app:project:task_filter_view' pk=element.id%}" name="{{element}}">{{element}}</a>
                <!--<a name="{{element}}">{{element}}</a>-->
            </li>
            {%endfor%}
</ul>
            {% endif %}
            <div id="legal">
                <a id="mentions" href="{% url 'vivs_app:project:mentions_legales' %}">mentions légales</a>
                <p id="copyright">©2016 Viviana Paga</p>
            </div>

        </div>
        <div id="main-content" class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-3 main">
            {% block CONTENT %}{% endblock %}
        </div>
      </div>
    </div>

    <!--<footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    {% bootstrap_javascript %}
    <script type="text/javascript" src="{% static 'js/svg.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/effects.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/svg2.js' %}" charset="utf-8"></script>

</body>
</html>

{% endspaceless %}

vivs/templates/vivs/about.html
{% extends 'base.html' %}
{% load staticfiles %} <!-- per caricare i file della cartella "static" che chiederemo al server di cariare poiche django non legge velocemente altri file diversi da python -->

{% block TITLE%} Viv-s | About me {% endblock %}

{% block CONTENT %}
            <div id="about">
                <!--<h3>about me</h3>-->
                <p>Je suis une webdesigner et développer basée à Paris.
                    <br>
                    J’aime l’interdisciplinarité et le croisement d’idées et de domaines.
                    <br>
                    Pendant des études en mathématiques, j’en ai fait en graphisme.
                    <br>Après je me suis rapprochée à la création web, en développant compétences dans le frontend et le backend.
                    <br>J’aime les projets qui me permettent de mélanger mes divers connaissances acquises.</p>
                <a href="/media/download/CV_Viviana_Paga_2016.pdf" download>CV à télécharger</a>

                <!--<object id="svg_about" type="image/svg+xml" data="{% static 'svg/about.svg' %}" class="about-img">
                    about image <!-- fallback image in CSS
                </object>-->
            </div>
{% endblock %}

vivs/templates/vivs/contact.html
{% extends 'base.html' %}

{% block TITLE%} Viv-s | Contacts {% endblock %}

{% block CONTENT %}
    <div id="contacts">
            <h3>contacts</h3>
            <!--<h5>viv-s is a brand of viviana paga</h5>-->

            <p>contact me by mail or telephone</p>
            <a href="mailto:viviana.paga@hotmail.it">viviana.paga@hotmail.it</a>
            <p>+33668279821</p>
    </div>
{% endblock %}

vivs/templates/vivs/index.html
{% extends 'base.html' %}

{% block TITLE%} Viv-s {% endblock %}

{% block CONTENT %}
              <!--  <div class="container-fluid">
             {% for element in project_list %}
                    <div id="cover-container" class="">
                        <a href="{% url 'vivs_app:project:project_detail'  %}">
                         {% if element.cover %}
                            <img src="{{ element.cover.url }}" />
                          {% endif %}
                        </a>
                    </div>
                {%endfor%}
                </div> -->
{% endblock %}

vivs/templates/vivs/mentions-legales.html
{% extends 'base.html' %}

{% block TITLE%} Viv-s | Mentions légales {% endblock %}

{% block CONTENT %}

<h2>Informations légales</h2>
<h3>1. Présentation du site.</h3>
<p>En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé aux utilisateurs du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
<p><strong>Propriétaire</strong> : Viviana Paga – – 46 rue Saint-Sébastien 75011 Paris<br />
<strong>Créateur</strong> : <a href="www.viv-s.com">Viviana Paga</a><br />
<strong>Responsable publication</strong> : Viviana Paga – viviana.paga@hotmail.it<br />
Le responsable publication est une personne physique ou une personne morale.<br />
<strong>Webmaster</strong> : Viviana Paga – viviana.paga@hotmail.it<br />
<strong>Hébergeur</strong> : OVH – 2 rue Kellermann 59100 Roubaix France<br />
Crédits : les mentions légales ont été générées et offertes par Subdelirium <a target="_blank" href="http://www.subdelirium.com/competences/creation-de-sites-web/" alt="creation site web">création de site web</a></p>

<h3>2. Conditions générales d’utilisation du site et des services proposés.</h3>
<p>L’utilisation du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> sont donc invités à les consulter de manière régulière.</p>
<p>Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par Viviana Paga, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
<p>Le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> est mis à jour régulièrement par Viviana Paga. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
<h3>3. Description des services fournis.</h3>
<p>Le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> a pour objet de fournir une information concernant l’ensemble des activités de la société.</p>
<p>Viviana Paga s’efforce de fournir sur le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> des informations aussi précises que possible. Toutefois, il ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</p>
<p>Tous les informations indiquées sur le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
<h3>4. Limitations contractuelles sur les données techniques.</h3>
<p>Le site utilise la technologie JavaScript.</p>
<p>Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour</p>
<h3>5. Propriété intellectuelle et contrefaçons.</h3>
<p>Viviana Paga est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.</p>
<p>Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : Viviana Paga.</p>
<p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
<h3>6. Limitations de responsabilité.</h3>
<p>Viviana Paga ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site www.viv-s.com, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
<p>Viviana Paga ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a>.</p>
<p>Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. Viviana Paga se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, Viviana Paga se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
<h3>7. Gestion des données personnelles.</h3>
<p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
<p>A l'occasion de l'utilisation du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a>, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur.</p>
<p> En tout état de cause Viviana Paga ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a>. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> l’obligation ou non de fournir ces informations.</p>
<p>Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
<p>Aucune information personnelle de l'utilisateur du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de Viviana Paga et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a>.</p>
<p>Le site n'est pas déclaré à la CNIL car il ne recueille pas d'informations personnelles. .</p>
<p>Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
<h3>8. Liens hypertextes et cookies.</h3>
<p>Le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Viviana Paga. Cependant, Viviana Paga n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
<p>La navigation sur le site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
<p>Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies :</p>
<p>Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok.</p>
<p>Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l'onglet Options. Cliquer sur l'onglet Vie privée.
Paramétrez les Règles de conservation sur : utiliser les paramètres personnalisés pour l'historique. Enfin décochez-la pour désactiver les cookies.</p>
<p>Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur Paramètres de contenu. Dans la section "Cookies", vous pouvez bloquer les cookies.</p>
<p>Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur préférences. Dans l'onglet "Confidentialité", vous pouvez bloquer les cookies.</p>

<h3>9. Droit applicable et attribution de juridiction.</h3>
<p>Tout litige en relation avec l’utilisation du site <a href="http://www.viv-s.com/" title="Viviana Paga - www.viv-s.com">www.viv-s.com</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
<h3>10. Les principales lois concernées.</h3>
<p>Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés.</p>
<p> Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.</p>
<h3>11. Lexique.</h3>
<p>Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
<p>Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>

{% endblock %}

vivs/templates/vivs/task_filter.html
{% extends 'base.html' %}

{% block TITLE%} Viv-s | {{task_filter}} works {% endblock %}

{% block CONTENT %}

            <!--<h4>filter : {{task_filter}} </h4>
            <p>projects :  </p>
                <ul>
                {% for element in task_filter.projects.all %}
                <li><a href="{% url 'vivs_app:project:project_detail' %}">{{element}}</a></li>
                {%endfor%}
                </ul>-->

{% endblock %}

vivs/templates/vivs/works.html
{% extends 'base.html' %}

{% block TITLE%} Viv-s | All works {% endblock %}

{% block CONTENT %}
            <!--<h3>works</h3>

            <ul>
                {% for element in works %}
                    <li><a href="{% url 'vivs_app:project:project_detail' %}">{{element}}</a></li>
                {%endfor%}
            </ul>-->
{% endblock %}